name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node environment
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Check types
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Check code style
        run: yarn lint

      - name: Check formatting
        run: yarn format-check
